version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: zenadmin
      POSTGRES_PASSWORD: temp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5445:5432"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
        - 5672:5672
        - 15672:15672
volumes:
  postgres:
